version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000" 
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0

  db:
    image: ncicto/chromadb-chroma
    volumes:
      - chromadb_data:/var/lib/chromadb  
    environment:
      - CHROMADB_ROOT_PASSWORD=root
      - CHROMADB_DATABASE=mydatabase
      - CHROMADB_USER=user
      - CHROMADB_PASSWORD=password

volumes:
  chromadb_data:
